
---
- hosts: web
  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: present
    - name: Start apache server
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Copy using inline data
      copy:
        src: /home/ansible/files/index.html
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0644
        backup: yes