---
- name: web servers
  hosts: web
  tasks:
    - name: Install packages
      package:
        name: "{{item}}"
        state: present
      loop:
        - apache2
        - php
        - php-mysql
        - git
        - lynx
      notify: restart apache
      tags:
        - base
    - name: Delete index.html from installation
      file:
        path: /var/www/html/index.html
        state: absent
    - name: deploy index.php
      git:
        repo: "{{ repository }}"
        dest: "{{ document_root_path }}"
      tags:
        - content
    - name: vhost config block
      block:
      - name: Copy conf file to dir of available sites
      # Note: In the Ubunutu / Apache2 configtutorial they suggest to copy a 
      #       a default config file and edit it line by line. We simply created 
      #       a minimal config file.
        copy:
          src: files/ansible_site.conf
          dest: "{{ sites_available_dir }}ansible.conf"
          owner: root
          group: root
          mode: 0644
        tags:
          - test
        notify: restart apache
      - name: Activating VirtualHostFile
        command: 
          cmd: a2ensite ansible.conf
          chdir: "{{ sites_available_dir }}"
        tags:
          - test
        notify: restart apache

    # End of the vhost config block

    - name: install hello world script with db
      copy:
        src: files/db.php
        #dest: "{{ document_root_path }}db.php"
        dest: "{{ document_root_path }}"
        mode: 0775
      tags:
        - content
        - test
        
    # - name: allow TCP traffic
    #   firewalld:
    #     port: 80/tcp
    #     permanent: true
    #     state: enabled
    #     immediate: true
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted