
---
- hosts: web
  tasks:
    - name: Install packages
      package:
        name: "{{item}}"
        state: present
      loop:
        - apache2
        - php
    - name: Start apache server
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Copy using inline data
      copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0644
        backup: yes
      loop:
        - files/index.html
        - files/index.php
    - name: Delete index.html
      file:
        path: /var/www/html/index.html
        state: absent
    - name: Restart apache
      service:
        name: apache2
        state: restarted
