version: '3'
services:
  controller:
    container_name: controller
    build:
      context: ./
      dockerfile: Dockerfile-controller
    restart: always
    depends_on:
      - lb1
      - web1
      - web2
      - db1
    ports:
      - '22:22'
    volumes:
      - ../controller-mountpoints/home.ansible:/home/ansible
      - ../controller-mountpoints/etc.ansible:/etc/ansible
  lb1:
    container_name: lb1
    build:
      context: ./
      dockerfile: Dockerfile-node

  web1:
    container_name: web1
    build:
      context: ./
      dockerfile: Dockerfile-node
  web2:
    container_name: web2
    build:
      context: ./
      dockerfile: Dockerfile-node

  db1:
    container_name: db1
    build:
      context: ./
      dockerfile: Dockerfile-node
