version: '3'
services:
  controller:
    container_name: controller
    build:
      context: ./
      dockerfile: Dockerfile-controller
    restart: always
    hostname: 'controller-host'
    depends_on:
      - lb1
      - web1
      - web2
      - db1
    ports:
      - '22:22'
    volumes:
      - ../controller-mountpoints/home.ansible:/home/ansible
      - ../controller-mountpoints/etc.ansible:/etc/ansible

  lb1:
    container_name: lb1
    build:
      context: ./
      dockerfile: Dockerfile-node
    hostname: 'lb1-host'
    ports:
      - '1001:80'

  web1:
    container_name: web1
    build:
      context: ./
      dockerfile: Dockerfile-node
    hostname: 'web1-host'
    ports:
      - '1011:80'

  web2:
    container_name: web2
    build:
      context: ./
      dockerfile: Dockerfile-node
    hostname: 'web2-host'
    ports:
      - '1012:80'

  db1:
    container_name: db1
    hostname: 'db1-host'
    build:
      context: ./
      dockerfile: Dockerfile-node
   