version: '3'
services:
  controller:
    container_name: controller
    build:
      context: ./
      dockerfile: Dockerfile-controller
    restart: always
    command: tail -F anything
    depends_on:
      - lb1
      - web1
      - web2
      - db1
    ports:
      - '22:22'
    volumes:
      - ../controller-mountpoints/home.ansible:/home/ansible
      - ../controller-mountpoints/etc.ansible:/etc/ansible
  lb1:
    container_name: lb1
    image: 'jdeathe/centos-ssh:2.6.1'
    command: tail -F anything

  web1:
    container_name: web1
    image: 'jdeathe/centos-ssh:2.6.1'
    command: tail -F anything
  web2:
    container_name: web2
    image: 'jdeathe/centos-ssh:2.6.1'
    command: tail -F anything
  db1:
    container_name: db1
    image: 'jdeathe/centos-ssh:2.6.1'
    command: tail -F anything
