FROM   ubuntu:18.04
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install systemd
RUN apt-get -y install openssh-client
RUN apt-get -y install openssh-server

# Ansible needs python on the nodes it wants to control
RUN apt-get -y install python
RUN apt-get -y install python-apt

#### For dev purposes ####
# Set root as pw for root user
RUN echo "root:root" | chpasswd
RUN apt-get -y install nano

# Place and run our specific start script
COPY ./start-node /bin/start

CMD ["/bin/start"]